FROM openjdk:17-alpine
# MAINTAINER baeldung.com

USER root

# Install Curl command
RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*

RUN mkdir /.aws
RUN mkdir /spring-config

COPY target/spring-boot-sample.jar spring-boot-sample.jar
COPY src/main/resources/application.properties /spring-config/application.properties
ENTRYPOINT ["java", "-Dhttp.nonProxyHosts=bucket.vpce-01ad73a99bd415b3c-3awu8laz.s3.ap-southeast-1.vpce.amazonaws.com","-jar","/spring-boot-sample.jar","--spring.config.location=file:///spring-config/application.properties"]
