apiVersion: v1
kind: Service
metadata:
  name: spring-boot-sample
  namespace: qdoc-dev-axa-kt-th
spec:
  selector:
    app: spring-boot-sample
    # deployment: spring-boot-sample
  ports:
    - name: spring-boot-sample-tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080