kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '95'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"api-process-psp-documents-cs"},"name":"api-process-psp-documents-cs","namespace":"data-api-uat-axa-kt-th","resourceVersion":"3840075472"},"spec":{"replicas":1,"revisionHistoryLimit":1,"selector":{"matchLabels":{"app":"api-process-psp-documents-cs"}},"strategy":{"activeDeadlineSeconds":21600,"recreateParams":{"timeoutSeconds":10000},"rollingParams":{"intervalSeconds":1,"maxSurge":"100%","maxUnavailable":"0%","timeoutSeconds":600,"updatePeriodSeconds":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"deployedDate":"1679306511"},"labels":{"app":"api-process-psp-documents-cs","application-name":"api-process-psp-documents-cs"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["api-process-psp-documents-cs"]}]},"topologyKey":"topology.kubernetes.io/zone"},"weight":100}]}},"containers":[{"env":[{"name":"TZ","value":"Asia/Bangkok"},{"name":"JAVA_OPTS","valueFrom":{"configMapKeyRef":{"key":"JAVA_OPTS","name":"api-process-psp-documents-cs"}}}],"envFrom":[{"configMapRef":{"name":"api-process-psp-documents-cs"}}],"image":"image-registry.openshift-image-registry.svc:5000/data-api-uat-axa-kt-th/api-process-psp-documents-cs:1.1.1","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":120,"periodSeconds":20,"successThreshold":1,"tcpSocket":{"port":8080},"timeoutSeconds":10},"name":"api-process-psp-documents-cs","ports":[{"containerPort":8080,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/api/v1/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":60,"timeoutSeconds":10},"resources":{"limits":{"cpu":"200m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"512Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/.aws","name":"aws-token"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"api-process-psp-documents-cs"},"name":"api-process-psp-documents-cs"},{"name":"aws-token","secret":{"defaultMode":420,"secretName":"api-psp-s3-aws-token"}}]}},"test":false}}
  resourceVersion: '4024924521'
  name: api-process-psp-documents-cs
  uid: 7a3b70b7-16f9-409f-9cf0-57e3e5164d11
  creationTimestamp: '2022-05-03T04:31:49Z'
  generation: 130
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-06-08T10:26:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:type': {}
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2023-02-28T10:53:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:deployedDate': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:application-name': {}
            'f:spec':
              'f:affinity':
                .: {}
                'f:podAntiAffinity':
                  .: {}
                  'f:preferredDuringSchedulingIgnoredDuringExecution': {}
              'f:containers':
                'k:{"name":"api-process-psp-documents-cs"}':
                  'f:envFrom': {}
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/.aws"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      .: {}
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    .: {}
                    'k:{"name":"JAVA_OPTS"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"api-process-psp-documents-cs"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"aws-token"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-05-03T17:30:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: data-api-uat-axa-kt-th
  labels:
    app: api-process-psp-documents-cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-process-psp-documents-cs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-process-psp-documents-cs
        application-name: api-process-psp-documents-cs
      annotations:
        deployedDate: '1679306511'
    spec:
      volumes:
        - name: api-process-psp-documents-cs
          configMap:
            name: api-process-psp-documents-cs
            defaultMode: 420
        - name: aws-token
          secret:
            secretName: api-psp-s3-aws-token
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: api-process-psp-documents-cs
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: api-process-psp-documents-cs
                  key: JAVA_OPTS
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: aws-token
              mountPath: /.aws
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: api-process-psp-documents-cs
          image: >-
            image-registry.openshift-image-registry.svc:5000/data-api-uat-axa-kt-th/api-process-psp-documents-cs:1.1.1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - api-process-psp-documents-cs
                topologyKey: topology.kubernetes.io/zone
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
status:
  observedGeneration: 130
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-03-20T10:03:23Z'
      lastTransitionTime: '2022-11-22T08:03:01Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "api-process-psp-documents-cs-6b97785795" has successfully
        progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-05-03T17:30:23Z'
      lastTransitionTime: '2023-05-03T17:30:23Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
